version: "3.9"

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - net
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - net
  web:
    tty: true
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/notificator
      - static:/notificator/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - postgres
  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/notificator
    depends_on:
      - postgres
      - redis
    networks:
      - net
  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/notificator
    depends_on:
      - postgres
      - redis
    networks:
      - net
volumes:
  pgdata:
  redisdata:
  static:
networks:
  net: {}
