global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 'web:8000'  

  - job_name: 'django-exporter' 
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'prometheus-exporter:9102'

# Правила оповещений можно настроить здесь
# или через интерфейс Grafana 
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"