# Generated by Django 4.2.6 on 2023-10-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('SENT', 'SENT'), ('NOT_SENT', 'NOT_SENT')], max_length=10),
        ),
    ]
