# Generated by Django 4.2.6 on 2023-10-22 16:47

from django.db import migrations, models
import django.db.models.deletion
import notification.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_client_timezone_alter_message_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[notification.validators.phone_number_validator], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='filter_client',
            field=models.JSONField(default=dict, validators=[notification.validators.filter_validator], verbose_name='фильтр клиентов'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notification.client', verbose_name='клиент'),
        ),
    ]
