# Generated by Django 4.2.6 on 2023-10-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time_interval',
            field=models.DurationField(blank=True, null=True, verbose_name='Временной интервал'),
        ),
    ]
